### ISSUE TITLE
How do you bring back the black bars?

### ISSUE THREAD

**Issue by t3dium** [he2a/mpv-config#2]
Great config overall except for the removal of black bars which lowers quality and cuts off a bit of content. Any way to bring it back?

I've tried pressing C and c to toggle it off, and also tried removing the auto-crop and manual-crop lua files in scripts but no luck.

EDIT: nvm, the issue wasn't related to your config

**Comment by he2a** [comment]
BTW if anyone has this problem, they can stop it by commenting or removing the profile `auto-fill` in `profiles.conf`.
