### ISSUE TITLE
Make OSC to show up whenever the mouse is moved

### ISSUE THREAD

**Issue by Phoenomenal** [he2a/mpv-config#4]
Hi.  are there any way to make OSC show up  whenever mouse moved like in a original mpv OSC ?    In this custom osc the only way to show progress bar is by hovering mouse to the bottom of the screen unfortunately.  

I know its probably possible by editing uosc.lua but cant make it work.  Need a helping hand .....

**Comment by he2a** [comment]
Its not ideal but you can change the `proximity_in` and `proximity_out` value in `uosc.conf` to some obscenely large value until all elements trigger area are overlapping each other. The file is located in `script-opts` folder.

**Comment by Phoenomenal** [comment]
Thanks, exactly what i wanted.
