### ISSUE TITLE
"dynaudnorm" stacks when using the 'Quit Watch Later' function

### ISSUE THREAD

**Issue by ZenicGH** [he2a/mpv-config#5]
When I use this function and open the file again, the audio filter stacks, causing the moments in between dialogue to be really loud.

**Comment by he2a** [comment]
Yeah I think I should just rewrite the script, something isn't really working well. For now if you are having problem, you can open afilter.lua in scripts folder and change `dnm_enabled` to `no`, that should stop the script from automatically activating it when it detects a movie is playing.

**Comment by ZenicGH** [comment]
Alright, thank you.
