### ISSUE TITLE
How do you show thumbnail in readme screenshot?

### ISSUE THREAD

**Issue by Zabooby** [he2a/mpv-config#6]
How do you toggle both the uosc ui and thumbnails at the same time? I've tried using the `toggle-ui` uosc command but it hides the buttons above the timeline when I show thumbnails.

**Comment by he2a** [comment]
Frankly I have no idea. Probably a limitation by uosc so might as well ask [there](https://github.com/tomasklaen/uosc/issues). BTW the preview picture is just a composite of three screenshot and not taken in one shot.

**Comment by Zabooby** [comment]
What tool did you use to combine the images?

**Comment by he2a** [comment]
Just photoshop 😅
