### ISSUE TITLE
Config no longer working.

### ISSUE THREAD

**Issue by NakedTrashPanda** [he2a/mpv-config#9]
It was working fine for months, then I decided to reset my PC and made sure to backup the config file. Reinstalled Windows, threw the config back into the location, and it doesn't work. Decide to redownload the config off here, same issue. The menu doesn't show up at all, the log shows some errors related to UOSC and CPlayer. 

Am I missing something?

Edit: So I managed to get it working with this config again, but having to install MPV through Chocolatey.

**Comment by he2a** [comment]
I guess the UOSC was out of date. I've updated the scripts so it should work now.
